"""initial_migration

Revision ID: 03445f65ceeb
Revises: 
Create Date: 2026-06-21 08:55:15.244564

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '03445f65ceeb'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=True)
    op.create_table('stock_exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_stock_exchanges_country'), 'stock_exchanges', ['country'], unique=False)
    op.create_index(op.f('ix_stock_exchanges_id'), 'stock_exchanges', ['id'], unique=False)
    op.create_index(op.f('ix_stock_exchanges_symbol'), 'stock_exchanges', ['symbol'], unique=True)
    op.create_table('exchange_buy_and_sell_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('bid', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ask', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_id', 'effective_date')
    )
    op.create_index(op.f('ix_exchange_buy_and_sell_rates_effective_date'), 'exchange_buy_and_sell_rates', ['effective_date'], unique=False)
    op.create_table('exchange_mid_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('mid', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_id', 'effective_date')
    )
    op.create_index(op.f('ix_exchange_mid_rates_effective_date'), 'exchange_mid_rates', ['effective_date'], unique=False)
    op.create_table('stock_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('yahoo_symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['stock_exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_companies_symbol'), 'stock_companies', ['symbol'], unique=True)
    op.create_index(op.f('ix_stock_companies_yahoo_symbol'), 'stock_companies', ['yahoo_symbol'], unique=True)
    op.create_table('stock_exchange_indexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_exchange_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['stock_exchange_id'], ['stock_exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_exchange_indexes_name'), 'stock_exchange_indexes', ['name'], unique=True)
    op.create_index(op.f('ix_stock_exchange_indexes_symbol'), 'stock_exchange_indexes', ['symbol'], unique=True)
    op.create_table('stock_exchange_indexe_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['stock_exchange_indexes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_id', 'trading_date')
    )
    op.create_index(op.f('ix_stock_exchange_indexe_rates_trading_date'), 'stock_exchange_indexe_rates', ['trading_date'], unique=False)
    op.create_table('stock_indexe_memberships',
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['stock_companies.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['stock_exchange_indexes.id'], ),
    sa.PrimaryKeyConstraint('index_id', 'company_id')
    )
    op.create_index(op.f('ix_stock_indexe_memberships_active'), 'stock_indexe_memberships', ['active'], unique=False)
    op.create_index(op.f('ix_stock_indexe_memberships_company_id'), 'stock_indexe_memberships', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_indexe_memberships_index_id'), 'stock_indexe_memberships', ['index_id'], unique=False)
    op.create_index(op.f('ix_stock_indexe_memberships_joined_at'), 'stock_indexe_memberships', ['joined_at'], unique=False)
    op.create_index(op.f('ix_stock_indexe_memberships_left_at'), 'stock_indexe_memberships', ['left_at'], unique=False)
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['stock_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'trading_date')
    )
    op.create_index(op.f('ix_stock_prices_trading_date'), 'stock_prices', ['trading_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_prices_trading_date'), table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index(op.f('ix_stock_indexe_memberships_left_at'), table_name='stock_indexe_memberships')
    op.drop_index(op.f('ix_stock_indexe_memberships_joined_at'), table_name='stock_indexe_memberships')
    op.drop_index(op.f('ix_stock_indexe_memberships_index_id'), table_name='stock_indexe_memberships')
    op.drop_index(op.f('ix_stock_indexe_memberships_company_id'), table_name='stock_indexe_memberships')
    op.drop_index(op.f('ix_stock_indexe_memberships_active'), table_name='stock_indexe_memberships')
    op.drop_table('stock_indexe_memberships')
    op.drop_index(op.f('ix_stock_exchange_indexe_rates_trading_date'), table_name='stock_exchange_indexe_rates')
    op.drop_table('stock_exchange_indexe_rates')
    op.drop_index(op.f('ix_stock_exchange_indexes_symbol'), table_name='stock_exchange_indexes')
    op.drop_index(op.f('ix_stock_exchange_indexes_name'), table_name='stock_exchange_indexes')
    op.drop_table('stock_exchange_indexes')
    op.drop_index(op.f('ix_stock_companies_yahoo_symbol'), table_name='stock_companies')
    op.drop_index(op.f('ix_stock_companies_symbol'), table_name='stock_companies')
    op.drop_table('stock_companies')
    op.drop_index(op.f('ix_exchange_mid_rates_effective_date'), table_name='exchange_mid_rates')
    op.drop_table('exchange_mid_rates')
    op.drop_index(op.f('ix_exchange_buy_and_sell_rates_effective_date'), table_name='exchange_buy_and_sell_rates')
    op.drop_table('exchange_buy_and_sell_rates')
    op.drop_index(op.f('ix_stock_exchanges_symbol'), table_name='stock_exchanges')
    op.drop_index(op.f('ix_stock_exchanges_id'), table_name='stock_exchanges')
    op.drop_index(op.f('ix_stock_exchanges_country'), table_name='stock_exchanges')
    op.drop_table('stock_exchanges')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
