"""empty message

Revision ID: 44a1c6fe6026
Revises: 478ffbccdd42
Create Date: 2026-06-02 07:06:38.971923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a1c6fe6026'
down_revision: Union[str, Sequence[str], None] = '478ffbccdd42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rates_effective_date'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('mid_rate', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('bid_rate', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('ask_rate', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], name=op.f('exchange_rates_currency_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exchange_rates_pkey')),
    sa.UniqueConstraint('currency_id', 'effective_date', name=op.f('exchange_rates_currency_id_effective_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_exchange_rates_effective_date'), 'exchange_rates', ['effective_date'], unique=False)
    # ### end Alembic commands ###
