"""empty message

Revision ID: 5d3b29634109
Revises: 03445f65ceeb
Create Date: 2026-06-21 15:34:06.617272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d3b29634109'
down_revision: Union[str, Sequence[str], None] = '03445f65ceeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_indexe_memberships',
    sa.Column('index_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('left_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['stock_companies.id'], name=op.f('stock_indexe_memberships_company_id_fkey')),
    sa.ForeignKeyConstraint(['index_id'], ['stock_exchange_indexes.id'], name=op.f('stock_indexe_memberships_index_id_fkey')),
    sa.PrimaryKeyConstraint('index_id', 'company_id', name=op.f('stock_indexe_memberships_pkey'))
    )
    op.create_index(op.f('ix_stock_indexe_memberships_left_at'), 'stock_indexe_memberships', ['left_at'], unique=False)
    op.create_index(op.f('ix_stock_indexe_memberships_joined_at'), 'stock_indexe_memberships', ['joined_at'], unique=False)
    op.create_index(op.f('ix_stock_indexe_memberships_index_id'), 'stock_indexe_memberships', ['index_id'], unique=False)
    op.create_index(op.f('ix_stock_indexe_memberships_company_id'), 'stock_indexe_memberships', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_indexe_memberships_active'), 'stock_indexe_memberships', ['active'], unique=False)
    op.create_table('exchange_mid_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('mid', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], name=op.f('exchange_mid_rates_currency_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exchange_mid_rates_pkey')),
    sa.UniqueConstraint('currency_id', 'effective_date', name=op.f('exchange_mid_rates_currency_id_effective_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_exchange_mid_rates_effective_date'), 'exchange_mid_rates', ['effective_date'], unique=False)
    op.create_table('stock_exchanges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_exchanges_pkey')),
    sa.UniqueConstraint('name', name=op.f('stock_exchanges_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_stock_exchanges_symbol'), 'stock_exchanges', ['symbol'], unique=True)
    op.create_index(op.f('ix_stock_exchanges_id'), 'stock_exchanges', ['id'], unique=False)
    op.create_index(op.f('ix_stock_exchanges_country'), 'stock_exchanges', ['country'], unique=False)
    op.create_table('stock_prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trading_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('adj_close', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['stock_companies.id'], name=op.f('stock_prices_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_prices_pkey')),
    sa.UniqueConstraint('company_id', 'trading_date', name=op.f('stock_prices_company_id_trading_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_stock_prices_trading_date'), 'stock_prices', ['trading_date'], unique=False)
    op.create_table('currencies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('currencies_pkey'))
    )
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=True)
    op.create_table('exchange_buy_and_sell_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('bid', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('ask', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], name=op.f('exchange_buy_and_sell_rates_currency_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exchange_buy_and_sell_rates_pkey')),
    sa.UniqueConstraint('currency_id', 'effective_date', name=op.f('exchange_buy_and_sell_rates_currency_id_effective_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_exchange_buy_and_sell_rates_effective_date'), 'exchange_buy_and_sell_rates', ['effective_date'], unique=False)
    op.create_table('stock_companies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('yahoo_symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['stock_exchanges.id'], name=op.f('stock_companies_exchange_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_companies_pkey'))
    )
    op.create_index(op.f('ix_stock_companies_yahoo_symbol'), 'stock_companies', ['yahoo_symbol'], unique=True)
    op.create_index(op.f('ix_stock_companies_symbol'), 'stock_companies', ['symbol'], unique=True)
    op.create_table('stock_exchange_indexes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_exchange_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stock_exchange_id'], ['stock_exchanges.id'], name=op.f('stock_exchange_indexes_stock_exchange_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_exchange_indexes_pkey'))
    )
    op.create_index(op.f('ix_stock_exchange_indexes_symbol'), 'stock_exchange_indexes', ['symbol'], unique=True)
    op.create_index(op.f('ix_stock_exchange_indexes_name'), 'stock_exchange_indexes', ['name'], unique=True)
    op.create_table('stock_exchange_indexe_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('index_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trading_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('adj_close', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['stock_exchange_indexes.id'], name=op.f('stock_exchange_indexe_rates_index_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_exchange_indexe_rates_pkey')),
    sa.UniqueConstraint('index_id', 'trading_date', name=op.f('stock_exchange_indexe_rates_index_id_trading_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_stock_exchange_indexe_rates_trading_date'), 'stock_exchange_indexe_rates', ['trading_date'], unique=False)
    # ### end Alembic commands ###
