"""empty message

Revision ID: 617f650b0cd6
Revises: abd2e8c80882
Create Date: 2026-06-07 08:23:14.015035

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "617f650b0cd6"
down_revision: str | Sequence[str] | None = "abd2e8c80882"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
