"""empty message

Revision ID: 6e21249ae489
Revises: 617f650b0cd6
Create Date: 2026-06-14 15:11:14.084019

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6e21249ae489"
down_revision: str | Sequence[str] | None = "617f650b0cd6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
