"""empty message

Revision ID: a82db5c3b88f
Revises: 6e21249ae489
Create Date: 2026-06-14 15:52:51.865498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82db5c3b88f'
down_revision: Union[str, Sequence[str], None] = '6e21249ae489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('yahoo_symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_symbol'), 'stock', ['symbol'], unique=True)
    op.create_index(op.f('ix_stock_yahoo_symbol'), 'stock', ['yahoo_symbol'], unique=True)
    op.create_table('stock_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trading_date')
    )
    op.create_index(op.f('ix_stock_price_trading_date'), 'stock_price', ['trading_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_price_trading_date'), table_name='stock_price')
    op.drop_table('stock_price')
    op.drop_index(op.f('ix_stock_yahoo_symbol'), table_name='stock')
    op.drop_index(op.f('ix_stock_symbol'), table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###
