"""empty message

Revision ID: abd2e8c80882
Revises: d75a178fc9ae
Create Date: 2026-06-06 08:32:50.390190

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "abd2e8c80882"
down_revision: str | Sequence[str] | None = "d75a178fc9ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
