"""empty message

Revision ID: ca5ad869142a
Revises: 5d3b29634109
Create Date: 2026-06-21 15:43:58.657016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5ad869142a'
down_revision: Union[str, Sequence[str], None] = '5d3b29634109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_exchanges', sa.Column('ticker', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_exchanges', 'ticker')
    # ### end Alembic commands ###
